using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace NetCodeGenerator.Serialization
{
    public class NetworkSerializationGenerator
    {
        public void Generate(string inputPath, string outputPath)
        {
            var syntaxTrees = new List<SyntaxTree>();

            foreach (var file in Directory.GetFiles(inputPath, "*.cs", SearchOption.AllDirectories))
            {
                if (file.EndsWith(".g.cs"))
                    continue;

                var text = File.ReadAllText(file);
                syntaxTrees.Add(CSharpSyntaxTree.ParseText(text));
            }

            TryAddToolAttributeSource(syntaxTrees);

            var compilation = CSharpCompilation.Create(
                "TempCompilation",
                syntaxTrees,
                new[]
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(List<>).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(Console).Assembly.Location),
                    MetadataReference.CreateFromFile(Path.Combine(AppContext.BaseDirectory, "Dependencies", "UnityEngine.CoreModule.dll")),
                    MetadataReference.CreateFromFile(Path.Combine(AppContext.BaseDirectory, "Dependencies", "Unity.Collections.dll")),
                    MetadataReference.CreateFromFile(Path.Combine(AppContext.BaseDirectory, "Dependencies", "Unity.Netcode.Runtime.dll")),
                    MetadataReference.CreateFromFile(Path.Combine(AppContext.BaseDirectory, "Dependencies", "UnityEngine.dll")),
                },
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            );

            var attributedTypes = CollectAttributedTypeNames(compilation, syntaxTrees);

            foreach (var tree in syntaxTrees)
            {
                var root = tree.GetRoot();

                foreach (var structDecl in root.DescendantNodes().OfType<StructDeclarationSyntax>())
                {
                    if (!HasGenerateNetworkSerializationAttribute(structDecl))
                        continue;

                    var model = compilation.GetSemanticModel(structDecl.SyntaxTree);

                    if (model.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol symbol)
                        continue;

                    if (!structDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
                    {
                        Console.WriteLine($"WARNING: {symbol.Name} must be declared `partial struct` so the generated file can merge with it.");
                    }

                    var ns = symbol.ContainingNamespace.ToDisplayString();
                    var isGlobalNamespace = ns == null || ns == "<global namespace>";
                    var structName = symbol.Name;

                    Console.WriteLine($"Generating NetworkSerializer for {structName}...");

                    var allFields = symbol.GetMembers()
                        .OfType<IFieldSymbol>()
                        .Where(f => !f.IsStatic).ToList();
                    
                    List<IFieldSymbol> fields = new();
                    HashSet<string> fieldsHash = new();
                    foreach (var field in allFields)
                    {
                        // Needed to avoid duplicate fields
                        if (fieldsHash.Contains(field.Name)) { continue; }

                        fields.Add(field);
                        fieldsHash.Add(field.Name);
                    }


                    var sb = new StringBuilder();

                    sb.AppendLine("// <auto-generated>");
                    sb.AppendLine($"// Serialization for {symbol.Name}");
                    sb.AppendLine("// </auto-generated>");
                    sb.AppendLine("using Unity.Netcode;");
                    sb.AppendLine("using System;");
                    sb.AppendLine("using Unity.Collections;");
                    sb.AppendLine("using System.Linq;");
                    sb.AppendLine();
                    if (!isGlobalNamespace)
                    {
                        sb.AppendLine($"namespace {ns}");
                        sb.AppendLine("{");
                    }
                    sb.AppendLine($"    public partial struct {structName} : INetworkSerializable, IEquatable<{structName}>");
                    sb.AppendLine("    {");

                    // NetworkSerialize
                    sb.AppendLine("        public void NetworkSerialize<T>(BufferSerializer<T> serializer) where T : IReaderWriter");
                    sb.AppendLine("        {");
                    foreach (var field in fields)
                    {
                        var fieldType = field.Type;

                        if (IsPrimitiveOrEnum(fieldType) || IsUnityBuiltinType(fieldType) || IsFixedString(fieldType))
                        {
                            sb.AppendLine($"            serializer.SerializeValue(ref {field.Name});");
                        }
                        else if (IsNetworkSerializableType(fieldType, attributedTypes))
                        {
                            sb.AppendLine($"            serializer.SerializeValue(ref {field.Name});");
                        }
                        else if (fieldType is INamedTypeSymbol namedType &&
                                 namedType.Name.StartsWith("FixedList") &&
                                 namedType.ContainingNamespace.ToDisplayString() == "Unity.Collections")
                        {
                            AddSerializationForFixedList(sb, field, namedType, attributedTypes);
                        }
                        else if (fieldType is INamedTypeSymbol namedType2 &&
                                namedType2.ConstructedFrom?.ToDisplayString() == "System.Collections.Generic.List<T>")
                        {
                            AddSerializationForList(sb, field, namedType2, attributedTypes);
                        }
                        else
                        {
                            // Fallback
                            sb.AppendLine($"            serializer.SerializeValue(ref {field.Name});");
                        }
                    }
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    // IEquatable<T>.Equals()
                    sb.AppendLine($"        public bool Equals({structName} other)");
                    sb.AppendLine("        {");
                    if (fields.Count == 0)
                    {
                        sb.AppendLine("            return true;");
                    }
                    else
                    {
                        sb.Append("            return ");
                        sb.Append(string.Join(" && ", fields.Select(f => GenerateEqualsExpression(f, attributedTypes))));
                        sb.AppendLine(";");
                    }
                    sb.AppendLine("        }");

                    sb.AppendLine("    }");
                    if (!isGlobalNamespace)
                    {
                        sb.AppendLine("}");
                    }

                    string fileName = $"{symbol.Name}_NetworkSerialization.g.cs";
                    string outputFile = Path.Combine(outputPath, fileName);
                    string content = sb.ToString();
                    if (File.Exists(outputFile) && File.ReadAllText(outputFile) == content)
                    {
                        Console.WriteLine($"Unchanged {fileName}");
                    }
                    else
                    {
                        File.WriteAllText(outputFile, content);
                        Console.WriteLine($"Wrote {fileName}");
                    }
                }
            }
        }

        static void TryAddToolAttributeSource(List<SyntaxTree> syntaxTrees)
        {
            string dir = AppContext.BaseDirectory;
            string[] candidates =
            {
                Path.GetFullPath(Path.Combine(dir, "..", "..", "..", "Serialization", "GenerateNetworkSerializationAttribute.cs")),
                Path.GetFullPath(Path.Combine(dir, "Serialization", "GenerateNetworkSerializationAttribute.cs"))
            };

            foreach (var path in candidates)
            {
                if (!File.Exists(path))
                    continue;

                syntaxTrees.Add(CSharpSyntaxTree.ParseText(File.ReadAllText(path)));
                return;
            }
        }

        static HashSet<string> CollectAttributedTypeNames(CSharpCompilation compilation, List<SyntaxTree> syntaxTrees)
        {
            var names = new HashSet<string>();
            foreach (var tree in syntaxTrees)
            {
                foreach (var structDecl in tree.GetRoot().DescendantNodes().OfType<StructDeclarationSyntax>())
                {
                    if (!HasGenerateNetworkSerializationAttribute(structDecl))
                        continue;

                    var model = compilation.GetSemanticModel(structDecl.SyntaxTree);
                    if (model.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol symbol)
                        continue;

                    names.Add(symbol.Name);
                    names.Add(symbol.ToDisplayString());
                }
            }

            return names;
        }

        static bool HasGenerateNetworkSerializationAttribute(StructDeclarationSyntax structDecl)
        {
            return structDecl.AttributeLists
                .SelectMany(al => al.Attributes)
                .Any(a =>
                {
                    string name = a.Name.ToString();
                    return name == "GenerateNetworkSerialization"
                        || name == "GenerateNetworkSerializationAttribute"
                        || name.EndsWith(".GenerateNetworkSerialization", StringComparison.Ordinal)
                        || name.EndsWith(".GenerateNetworkSerializationAttribute", StringComparison.Ordinal);
                });
        }

        static bool IsNetworkSerializableType(ITypeSymbol type, HashSet<string> attributedTypes)
        {
            if (ImplementsInterface(type, "Unity.Netcode.INetworkSerializable") ||
                ImplementsInterface(type, "Unity.Netcode.INetworkSerializeByMemcpy"))
            {
                return true;
            }

            return attributedTypes.Contains(type.Name) || attributedTypes.Contains(type.ToDisplayString());
        }

        private static bool IsPrimitiveOrEnum(ITypeSymbol type)
        {
            return type.IsValueType && (
                type.SpecialType != SpecialType.None ||
                type.TypeKind == TypeKind.Enum
            );
        }

        private static bool IsUnityBuiltinType(ITypeSymbol type)
        {
            string[] unityBuiltinTypes = new[]
            {
                "UnityEngine.Vector2",
                "UnityEngine.Vector3",
                "UnityEngine.Vector4",
                "UnityEngine.Vector2Int",
                "UnityEngine.Vector3Int",
                "UnityEngine.Quaternion",
                "UnityEngine.Color",
                "UnityEngine.Color32",
                "UnityEngine.Ray",
                "UnityEngine.Ray2D"
            };
            return unityBuiltinTypes.Contains(type.ToDisplayString());
        }

        private static bool IsFixedString(ITypeSymbol type)
        {
            string[] fixedStrings = new[]
            {
                "Unity.Collections.FixedString32Bytes",
                "Unity.Collections.FixedString64Bytes",
                "Unity.Collections.FixedString128Bytes",
                "Unity.Collections.FixedString512Bytes",
                "Unity.Collections.FixedString4096Bytes"
            };
            return fixedStrings.Contains(type.ToDisplayString());
        }

        private static bool ImplementsInterface(ITypeSymbol type, string interfaceName)
        {
            return type.AllInterfaces.Any(i => i.ToDisplayString() == interfaceName);
        }

        private static void AddSerializationForList(StringBuilder sb, IFieldSymbol field, INamedTypeSymbol namedType, HashSet<string> attributedTypes)
        {
            var elementType = namedType.TypeArguments[0];
            var elementTypeName = elementType.ToDisplayString();

            bool isINetworkSerializable = IsNetworkSerializableType(elementType, attributedTypes);

            sb.AppendLine();
            sb.AppendLine($"            // {field.Name}");
            sb.AppendLine($"            // WARNING: List<{elementTypeName}> incurs GC allocations and is not recommended for production use.");
            sb.AppendLine($"            if (serializer.IsWriter)");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var writer = serializer.GetFastBufferWriter();");
            sb.AppendLine($"                writer.WriteValueSafe({field.Name}?.Count ?? 0);");
            sb.AppendLine($"                if ({field.Name} != null)");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    for (int i = 0; i < {field.Name}.Count; i++)");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        var elem = {field.Name}[i];");

            if (isINetworkSerializable)
            {
                sb.AppendLine($"                        elem.NetworkSerialize(serializer);");
            }
            else
            {
                sb.AppendLine($"                        serializer.SerializeValue(ref elem);");
            }

            sb.AppendLine($"                    }}");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
            sb.AppendLine($"            else");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var reader = serializer.GetFastBufferReader();");
            sb.AppendLine($"                reader.ReadValueSafe(out int count);");
            sb.AppendLine($"                if ({field.Name} == null) {field.Name} = new System.Collections.Generic.List<{elementTypeName}>(count); else {field.Name}.Clear();");
            sb.AppendLine($"                for (int i = 0; i < count; i++)");
            sb.AppendLine($"                {{");

            sb.AppendLine($"                    {elementTypeName} elem = default;");

            if (isINetworkSerializable)
            {
                sb.AppendLine($"                    elem.NetworkSerialize(serializer);");
            }
            else
            {
                sb.AppendLine($"                    serializer.SerializeValue(ref elem);");
            }

            sb.AppendLine($"                    {field.Name}.Add(elem);");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
        }

        private static void AddSerializationForFixedList(StringBuilder sb, IFieldSymbol field, INamedTypeSymbol namedType, HashSet<string> attributedTypes)
        {
            var elementType = namedType.TypeArguments[0];
            var elementTypeName = elementType.ToDisplayString();

            bool isINetworkSerializable = IsNetworkSerializableType(elementType, attributedTypes);

            sb.AppendLine();
            sb.AppendLine($"            // {field.Name}");
            sb.AppendLine($"            if (serializer.IsWriter)");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var writer = serializer.GetFastBufferWriter();");
            sb.AppendLine($"                int count = {field.Name}.Length;");
            sb.AppendLine($"                writer.WriteValueSafe(count);");
            sb.AppendLine($"                for (int i = 0; i < count; i++)");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    var elem = {field.Name}[i];");

            if (isINetworkSerializable)
            {
                sb.AppendLine($"                    elem.NetworkSerialize(serializer);");
            }
            else
            {
                sb.AppendLine($"                    writer.WriteValueSafe(elem);");
            }

            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
            sb.AppendLine($"            else");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var reader = serializer.GetFastBufferReader();");
            sb.AppendLine($"                reader.ReadValueSafe(out int count);");
            sb.AppendLine($"                {field.Name}.Clear();");
            sb.AppendLine($"                for (int i = 0; i < count; i++)");
            sb.AppendLine($"                {{");

            if (isINetworkSerializable)
            {
                sb.AppendLine($"                    {elementTypeName} elem = default;");
                sb.AppendLine($"                    elem.NetworkSerialize(serializer);");
            }
            else
            {
                sb.AppendLine($"                    {elementTypeName} elem;");
                sb.AppendLine($"                    reader.ReadValueSafe(out elem);");
            }

            sb.AppendLine($"                    {field.Name}.Add(elem);");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
        }

        private static string GenerateEqualsExpression(IFieldSymbol field, HashSet<string> attributedTypes)
        {
            if (IsPrimitiveOrEnum(field.Type) || IsUnityBuiltinType(field.Type) || IsFixedString(field.Type))
            {
                return $"{field.Name} == other.{field.Name}";
            }
            else if (field.Type is INamedTypeSymbol namedType &&
                     namedType.Name.StartsWith("FixedList") &&
                     namedType.ContainingNamespace.ToDisplayString() == "Unity.Collections")
            {
                return $"{field.Name}.Equals(other.{field.Name})";
            }
            else if (field.Type is INamedTypeSymbol namedType2 &&
                            namedType2.ConstructedFrom?.ToDisplayString() == "System.Collections.Generic.List<T>")
            {
                return $"{field.Name}.SequenceEqual(other.{field.Name})";
            }
            else if (IsNetworkSerializableType(field.Type, attributedTypes) ||
                     ImplementsInterface(field.Type, $"System.IEquatable<{field.Type.ToDisplayString()}>"))
            {
                return $"{field.Name}.Equals(other.{field.Name})";
            }
            else
            {
                // fallback: == (may fail if operator== is not defined)
                return $"{field.Name} == other.{field.Name}";
            }
        }
    }
}
